ui5Lumira: Login scrip fix implemented
timostark/ui5-testcafe-selector-utils pull request #2
Opened 2021-11-16 14:10 UTC by tiyanishivambu

Uncertain about the page elements id's, they seem to be dynamic.

2021-11-16 15:29 UTC, timostark requested changes

2021-11-16 15:29 UTC, timostark commented on src/ui5Lumira.ts
> +            .typeText(ui5().domQuery('#_input4-inner'), pw, { anonymize: true })
do not use generic ids (i see that it is almost impossible to use sth. else, but please try ui5().element('sap.m.Input').positionInAggregation(1); here)

2021-11-17 09:42 UTC, tiyanishivambu commented
Hi Timo, change pushed, please have a look

2021-11-19 12:35 UTC, tiyanishivambu commented
Tested the change locally and it works

2022-01-17 21:12 UTC, merged